version: "2"

services:
  postgres:
    image: postgres:11.6-alpine
    command: -c 'max_connections=200'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
